services:
  client:
    container_name: hydro-harbor-client
    build:
      context: ./hydro-harbor-client
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
    ports:
      - 3000:3000
    depends_on:
      - server
    profiles:
      - dockerized

  server:
    container_name: hydro-harbor-server
    build:
      context: ./hydro-harbor-server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - DB_URL=${DB_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db
    profiles:
      - dockerized

  db:
    image: mongo
    container_name: hydro-harbor-db
    environment:
      MONGO_INITDB_DATABASE: hydro-harbor-db
    ports:
      - 27017:27017
    profiles:
      - dockerized
      - local
